### ISSUE TITLE
unprintable ascii / utf-8 codes throws a python error

### ISSUE THREAD

**Issue by hojuruku** [gmbnomis/uboot-mdb-dump#1]
Great script, but I ran into trouble. 

```
python3.4 uboot_mdb_to_image.py <../routerdump.txt > /dev/null
Traceback (most recent call last):
  File "uboot_mdb_to_image.py", line 28, in <module>
    asciiReader = codecs.getreader('ascii')
NameError: name 'codecs' is not defined
```
And this didn't work either..
```
PYTHONIOENCODING="ascii" python3.4 uboot_mdb_to_image.py <../routerdump.txt > /dev/null
Traceback (most recent call last):
  File "uboot_mdb_to_image.py", line 31, in <module>
    for line in sys.stdin:
  File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 5609: ordinal not in range(128)
```

I might just have to go after the binary output only, and run the dump twice or 3 times and diff it to make sure the data was exported OK.
```
 sed 's/[0-9a-f]\{8\}: //g' | cut -d " " -f 1-16 > <hexonly>
 xxd -r -p <hex> > <binary>
```
Credit to plntyk on openwrt irc for that 2 liner.

**Comment by hojuruku** [comment]
```
hojuruku uboot-mdb-dump # PYTHONIOENCODING="ascii" python3.4 uboot_mdb_to_image.py <../routerdump.txt  > /home/lmc/routerbackup.bin
hojuruku uboot-mdb-dump # du -sh /home/lmc/routerbackup.bin 
8.0M	/home/lmc/routerbackup.bin
```
I stand corrected. I did further investigation. The serial line had some scrambled characters, so I'll do my backup a few more times carefully and diff. Your script works, though it's parsing the text using utf-8 by default instead of ascii.

**Comment by gmbnomis** [comment]
Yes, parsing stdin as ASCII makes more sense. Thanks for pointing this out. I will change that.

**Comment by hojuruku** [comment]
line  5609 of my input file had scrambled non ascii characters from a flakey pl2303 grounding issue. 

ASCII does a better job of tracking those errors I guess - less valid characters that UTF-8
